# Generated by Django 4.2.25 on 2025-10-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoobooking',
            name='numAdults',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoobooking',
            name='numChildren',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoobooking',
            name='numInfants',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
