# Generated by Django 4.2.25 on 2025-10-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zooBooking',
            fields=[
                ('zooID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('arriveDate', models.DateTimeField()),
                ('leaveDate', models.DateTimeField()),
            ],
        ),
    ]
